/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    products: Product;
    projects: Project;
    materials: Material;
    orders: Order;
    leads: Lead;
    media: Media;
    users: User;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    products: ProductsSelect<false> | ProductsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    materials: MaterialsSelect<false> | MaterialsSelect<true>;
    orders: OrdersSelect<false> | OrdersSelect<true>;
    leads: LeadsSelect<false> | LeadsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    home: Home;
    settings: Setting;
  };
  globalsSelect: {
    home: HomeSelect<false> | HomeSelect<true>;
    settings: SettingsSelect<false> | SettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products".
 */
export interface Product {
  id: number;
  name: string;
  status: 'borrador' | 'publicado' | 'archivado';
  /**
   * Se genera desde el nombre si lo dejas vacío.
   */
  slug?: string | null;
  line: 'stone' | 'design' | 'care';
  category:
    'mesa-comedor' | 'mesa-centro' | 'mesa-auxiliar' | 'consola' | 'lavamanos' | 'objeto' | 'cuidado' | 'proyecto';
  shortDescription: string;
  /**
   * Piedra primero. Ej.: Piedra natural · roble
   */
  materialsText: string;
  images?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  saleMode: 'inmediata' | 'pedido' | 'configurable' | 'cotizacion';
  /**
   * Se usa si no hay tamaños con precio propio.
   */
  basePrice?: number | null;
  priceDisplay?: ('fijo' | 'desde' | 'cotizar') | null;
  depositPercent?: number | null;
  leadTime?: string | null;
  /**
   * Solo para entrega inmediata.
   */
  stock?: number | null;
  stoneOptions?:
    | {
        label: string;
        swatch?: (number | null) | Media;
        priceDelta?: number | null;
        available?: boolean | null;
        id?: string | null;
      }[]
    | null;
  sizeOptions?:
    | {
        label: string;
        dimensions?: string | null;
        price: number;
        id?: string | null;
      }[]
    | null;
  baseOptions?:
    | {
        label: string;
        priceDelta?: number | null;
        id?: string | null;
      }[]
    | null;
  details?: string | null;
  care?: string | null;
  requiresInstallation?: boolean | null;
  signed?: boolean | null;
  featured?: boolean | null;
  order?: number | null;
  isExample?: boolean | null;
  relatedProjects?: (number | Project)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Describe lo que se ve. Ej.: "Mesa con cubierta de piedra y base en roble".
   */
  alt: string;
  /**
   * Para fotos de producto sobre fondo blanco: el sitio las funde con el fondo de la tarjeta.
   */
  studio?: boolean | null;
  /**
   * Márcala si no es una foto real de Caliza. El sitio la etiqueta como provisional.
   */
  provisional?: boolean | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Se genera desde el nombre si lo dejas vacío.
   */
  slug?: string | null;
  line: 'stone' | 'design' | 'care';
  city?: string | null;
  year?: number | null;
  /**
   * Ej.: Cocina y comedor
   */
  space?: string | null;
  /**
   * Piedra primero. Ej.: Piedra natural · roble · latón
   */
  materialsText?: string | null;
  challenge?: string | null;
  solution?: string | null;
  cover: number | Media;
  gallery?:
    | {
        image: number | Media;
        id?: string | null;
      }[]
    | null;
  featured?: boolean | null;
  isExample?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials".
 */
export interface Material {
  id: number;
  name: string;
  /**
   * Se genera desde el nombre si lo dejas vacío.
   */
  slug?: string | null;
  family: 'piedra' | 'madera' | 'metal' | 'textura';
  description?: string | null;
  recommendedUses?: string | null;
  cautions?: string | null;
  image?: (number | null) | Media;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders".
 */
export interface Order {
  id: number;
  number?: string | null;
  status:
    | 'pendiente_pago'
    | 'anticipo_pagado'
    | 'pagado'
    | 'seleccion_placa'
    | 'fabricacion'
    | 'saldo_pendiente'
    | 'despachado'
    | 'entregado'
    | 'cancelado';
  /**
   * Enlace privado de seguimiento para el cliente.
   */
  accessToken?: string | null;
  customerName: string;
  customerPhone: string;
  customerEmail?: string | null;
  shipping: {
    city: string;
    address: string;
    propertyType?: string | null;
    floor?: string | null;
    elevator?: boolean | null;
    narrowStairs?: boolean | null;
    installation?: boolean | null;
    carrier?: string | null;
    trackingNumber?: string | null;
    trackingUrl?: string | null;
  };
  items: {
    product?: (number | null) | Product;
    name: string;
    config?: string | null;
    unitPrice: number;
    quantity: number;
    id?: string | null;
  }[];
  subtotal: number;
  shippingCost?: number | null;
  total: number;
  paymentPlan?: ('completo' | 'anticipo') | null;
  amountDueNow?: number | null;
  amountPaid?: number | null;
  payments?:
    | {
        provider?: string | null;
        reference?: string | null;
        transactionId?: string | null;
        amount?: number | null;
        method?: string | null;
        status?: ('PENDING' | 'APPROVED' | 'DECLINED' | 'VOIDED' | 'ERROR') | null;
        at?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Cada avance aparece en la página de seguimiento del cliente.
   */
  updates?:
    | {
        note: string;
        photo?: (number | null) | Media;
        at?: string | null;
        id?: string | null;
      }[]
    | null;
  utmSource?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads".
 */
export interface Lead {
  id: number;
  name: string;
  phone: string;
  city?: string | null;
  intent: 'proyecto' | 'pieza' | 'cuidado' | 'orientacion';
  channel?: ('whatsapp' | 'videollamada') | null;
  message?: string | null;
  utmSource?: string | null;
  status?: ('nuevo' | 'conversacion' | 'cotizado' | 'ganado' | 'perdido') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  resetPasswordRequestedAt?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'products';
        value: number | Product;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null)
    | ({
        relationTo: 'materials';
        value: number | Material;
      } | null)
    | ({
        relationTo: 'orders';
        value: number | Order;
      } | null)
    | ({
        relationTo: 'leads';
        value: number | Lead;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "products_select".
 */
export interface ProductsSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  slug?: T;
  line?: T;
  category?: T;
  shortDescription?: T;
  materialsText?: T;
  images?:
    | T
    | {
        image?: T;
        id?: T;
      };
  saleMode?: T;
  basePrice?: T;
  priceDisplay?: T;
  depositPercent?: T;
  leadTime?: T;
  stock?: T;
  stoneOptions?:
    | T
    | {
        label?: T;
        swatch?: T;
        priceDelta?: T;
        available?: T;
        id?: T;
      };
  sizeOptions?:
    | T
    | {
        label?: T;
        dimensions?: T;
        price?: T;
        id?: T;
      };
  baseOptions?:
    | T
    | {
        label?: T;
        priceDelta?: T;
        id?: T;
      };
  details?: T;
  care?: T;
  requiresInstallation?: T;
  signed?: T;
  featured?: T;
  order?: T;
  isExample?: T;
  relatedProjects?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  line?: T;
  city?: T;
  year?: T;
  space?: T;
  materialsText?: T;
  challenge?: T;
  solution?: T;
  cover?: T;
  gallery?:
    | T
    | {
        image?: T;
        id?: T;
      };
  featured?: T;
  isExample?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "materials_select".
 */
export interface MaterialsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  family?: T;
  description?: T;
  recommendedUses?: T;
  cautions?: T;
  image?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "orders_select".
 */
export interface OrdersSelect<T extends boolean = true> {
  number?: T;
  status?: T;
  accessToken?: T;
  customerName?: T;
  customerPhone?: T;
  customerEmail?: T;
  shipping?:
    | T
    | {
        city?: T;
        address?: T;
        propertyType?: T;
        floor?: T;
        elevator?: T;
        narrowStairs?: T;
        installation?: T;
        carrier?: T;
        trackingNumber?: T;
        trackingUrl?: T;
      };
  items?:
    | T
    | {
        product?: T;
        name?: T;
        config?: T;
        unitPrice?: T;
        quantity?: T;
        id?: T;
      };
  subtotal?: T;
  shippingCost?: T;
  total?: T;
  paymentPlan?: T;
  amountDueNow?: T;
  amountPaid?: T;
  payments?:
    | T
    | {
        provider?: T;
        reference?: T;
        transactionId?: T;
        amount?: T;
        method?: T;
        status?: T;
        at?: T;
        id?: T;
      };
  updates?:
    | T
    | {
        note?: T;
        photo?: T;
        at?: T;
        id?: T;
      };
  utmSource?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "leads_select".
 */
export interface LeadsSelect<T extends boolean = true> {
  name?: T;
  phone?: T;
  city?: T;
  intent?: T;
  channel?: T;
  message?: T;
  utmSource?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  studio?: T;
  provisional?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  resetPasswordRequestedAt?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home".
 */
export interface Home {
  id: number;
  heroImage: number | Media;
  heroEyebrow?: string | null;
  heroLine1?: string | null;
  heroLine2?: string | null;
  heroLine3?: string | null;
  heroText?: string | null;
  manifesto?: string | null;
  stoneImage: number | Media;
  designImage: number | Media;
  careImage: number | Media;
  historyText?: string | null;
  generations?:
    | {
        name: string;
        note?: string | null;
        id?: string | null;
      }[]
    | null;
  careSectionImage?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings".
 */
export interface Setting {
  id: number;
  /**
   * Formato internacional sin "+". Ej.: 573001234567
   */
  whatsappNumber: string;
  instagramUrl?: string | null;
  tiktokUrl?: string | null;
  shippingCities?:
    | {
        city: string;
        cost: number;
        id?: string | null;
      }[]
    | null;
  /**
   * Se muestra como "por confirmar" si es 0.
   */
  defaultShippingCost?: number | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home_select".
 */
export interface HomeSelect<T extends boolean = true> {
  heroImage?: T;
  heroEyebrow?: T;
  heroLine1?: T;
  heroLine2?: T;
  heroLine3?: T;
  heroText?: T;
  manifesto?: T;
  stoneImage?: T;
  designImage?: T;
  careImage?: T;
  historyText?: T;
  generations?:
    | T
    | {
        name?: T;
        note?: T;
        id?: T;
      };
  careSectionImage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "settings_select".
 */
export interface SettingsSelect<T extends boolean = true> {
  whatsappNumber?: T;
  instagramUrl?: T;
  tiktokUrl?: T;
  shippingCities?:
    | T
    | {
        city?: T;
        cost?: T;
        id?: T;
      };
  defaultShippingCost?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}